# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-08 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangaki', '0025_auto_20151220_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='suggestions',
            field=models.ManyToManyField(blank=True, to='mangaki.Suggestion'),
        ),
    ]
