# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 19:03
from __future__ import unicode_literals

from django.db import migrations, models

def add_category_id(apps, schema_editor):
    Anime = apps.get_model("mangaki", "Anime")
    Album = apps.get_model("mangaki", "Album")
    Manga = apps.get_model("mangaki", "Manga")

    Anime.objects.update(category_id=0)
    Manga.objects.update(category_id=1)
    Album.objects.update(category_id=2)

def remove_category_id(apps, schema_editor):
    # Nothing to do, we are removing the field
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('mangaki', '0028_auto_20160124_1919_squashed_0029_auto_20160124_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='category_id',
            field=models.IntegerField(blank=True, choices=[(0, 'Anime'), (1, 'Manga'), (2, 'Album')], default=0),
            preserve_default=False,
        ),
        migrations.RunPython(
            code=add_category_id,
            reverse_code=remove_category_id,
        ),
    ]
