# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 19:03
from __future__ import unicode_literals

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('mangaki', '0028_auto_20160124_1919_squashed_0029_auto_20160124_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='category_id',
            field=models.IntegerField(blank=True, choices=[(0, 'Anime'), (1, 'Manga'), (2, 'Album')], default=0, db_index=True),
            preserve_default=False,
        ),
        migrations.RunSQL(
            [
                "UPDATE mangaki_work SET category_id = 0 WHERE EXISTS (SELECT work_ptr_id FROM mangaki_anime WHERE work_ptr_id = mangaki_work.id);",
                "UPDATE mangaki_work SET category_id = 1 WHERE EXISTS (SELECT work_ptr_id FROM mangaki_manga WHERE work_ptr_id = mangaki_work.id);",
                "UPDATE mangaki_work SET category_id = 2 WHERE EXISTS (SELECT work_ptr_id FROM mangaki_album WHERE work_ptr_id = mangaki_work.id);",
            ],
            migrations.RunSQL.noop
        ),
    ]
