# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 00:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

def add_categories(apps, schema_editor):
    Category = apps.get_model("mangaki", "Category")
    Category.objects.bulk_create([
        Category(slug='anime', name="Anime"),
        Category(slug='manga', name="Manga"),
        Category(slug='album', name="Album"),
    ])

def populate_categories(apps, schema_editor):
    Category = apps.get_model("mangaki", "Category")
    Anime = apps.get_model("mangaki", "Anime")
    Manga = apps.get_model("mangaki", "Manga")
    Album = apps.get_model("mangaki", "Album")

    Anime.objects.update(category=Category.objects.get(slug='anime'))
    Manga.objects.update(category=Category.objects.get(slug='manga'))
    Album.objects.update(category=Category.objects.get(slug='album'))

class Migration(migrations.Migration):

    dependencies = [
        ('mangaki', '0001_squashed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(db_index=True, max_length=10)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.RunPython(add_categories, migrations.RunPython.noop),
        migrations.AddField(
            model_name='work',
            name='category',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='mangaki.Category'),
            preserve_default=False,
        ),
        migrations.RunPython(populate_categories, migrations.RunPython.noop),
    ]
