# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangaki', '0029_work_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='controversy',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='work',
            name='nb_dislikes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='work',
            name='nb_likes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='work',
            name='nb_ratings',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='work',
            name='sum_ratings',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterIndexTogether(
            name='work',
            index_together=set([('category_id', 'nb_ratings'), ('category_id', 'controversy')]),
        ),
        migrations.RunSQL(
            "CREATE INDEX mangaki_work_random ON mangaki_work ((nb_dislikes <= 17 AND nb_likes >= ((nb_dislikes * 3.0)) AND nb_ratings >= 28));",
            "DROP INDEX IF EXISTS mangaki_work_random;",
        ),
    ]
