# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 19:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mangaki', '0030_auto_20160127_1914'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Deck',
        ),
    ]
