# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-09 10:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('mangaki', '0032_auto_20160409_1024'), ('mangaki', '0033_auto_20160409_1028')]

    dependencies = [
        ('mangaki', '0031_delete_deck'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mangaki.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='staff',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mangaki.Role'),
        ),
        migrations.AddField(
            model_name='staff',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mangaki.Work'),
        ),
        migrations.AddField(
            model_name='work',
            name='artists',
            field=models.ManyToManyField(blank=True, through='mangaki.Staff', to='mangaki.Artist'),
        ),
        migrations.AlterUniqueTogether(
            name='staff',
            unique_together=set([('work', 'artist', 'role')]),
        ),
    ]
