# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-09 10:25
from __future__ import unicode_literals

from django.db import migrations

def create_stafftype(apps, schema_editor):
    Role = apps.get_model("mangaki", "Role")
    Role.objects.create(name="Scénariste", slug="writer")
    Role.objects.create(name="Mangaka", slug="mangaka")
    Role.objects.create(name="Auteur", slug="author")
    Role.objects.create(name="Compositeur", slug="composer")
    Role.objects.create(name="Réalisateur", slug="director")

class Migration(migrations.Migration):

    dependencies = [
        ('mangaki', '0033_stafftype'),
    ]

    operations = [
        migrations.RunPython(code=create_stafftype)
    ]
