# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-09 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangaki', '0035_populate_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='manga',
            name='genre',
        ),
        migrations.AddField(
            model_name='work',
            name='genre',
            field=models.ManyToManyField(to='mangaki.Genre'),
        ),
    ]
