# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-09 19:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mangaki', '0035_populate_staff'),
    ]

    operations = [
        migrations.RunSQL("""
        CREATE EXTENSION IF NOT EXISTS pg_trgm;
        CREATE EXTENSION IF NOT EXISTS unaccent;
        CREATE INDEX mangaki_search_work_upper ON mangaki_work USING gin(UPPER(UNACCENT(title)) gin_trgm_ops);
        CREATE INDEX mangaki_search_work       ON mangaki_work USING gin(UNACCENT(title)        gin_trgm_ops);
        """,
        """
        DROP INDEX mangaki_search_work_upper;
        DROP INDEX mangaki_search_work;
        """
        ),
    ]
