# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-09 19:11
from __future__ import unicode_literals

from django.db import migrations, models


def combine_names(apps, schema_editor):
    Artist = apps.get_model("mangaki", "Artist")
    for artist in Artist.objects.all():
        artist.name = "%s %s" % (artist.first_name, artist.last_name)
        artist.save()


class Migration(migrations.Migration):

    dependencies = [
        ('mangaki', '0035_populate_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.RunPython(combine_names),
    ]
