# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-10 18:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mangaki', '0032_rating_date'),
        ('mangaki', '0035_populate_staff'),
    ]

    operations = [
    ]
