# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-09 21:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def add_trivial_entries(apps, schema_editor):
    Artist = apps.get_model("mangaki", "Artist")
    ArtistSpelling = apps.get_model("mangaki", "ArtistSpelling")
    for artist in Artist.objects.all():
        ArtistSpelling.objects.get_or_create(was=artist.name, artist=artist)


class Migration(migrations.Migration):

    dependencies = [
        ('mangaki', '0036_artist_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistSpelling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('was', models.CharField(db_index=True, max_length=255)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mangaki.Artist')),
            ],
        ),
        migrations.RunPython(add_trivial_entries),
    ]
