# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-16 09:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mangaki', '0037_auto_20160410_1847'),
    ]

    operations = [
        # Inspired from https://wiki.postgresql.org/wiki/Deleting_duplicates
        migrations.RunSQL('''
DELETE FROM mangaki_rating
WHERE id IN (
    SELECT id
    FROM (SELECT id,
                 ROW_NUMBER() OVER (PARTITION BY user_id, work_id ORDER BY id DESC) AS rnum
          FROM mangaki_rating) t
    WHERE t.rnum > 1)
'''),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set([('user', 'work')]),
        ),
    ]
