# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-10 20:09
from __future__ import unicode_literals

from django.db import migrations

def populate_staff(apps, schema_editor):
    Role = apps.get_model("mangaki", "Role")
    Staff = apps.get_model("mangaki", "Staff")
    Album = apps.get_model("mangaki", "Album")

    composer = Role.objects.get(slug='composer')
    Staff.objects.bulk_create([
        Staff(work_id=work.id, artist_id=work.deprecated_composer_id, role=composer)
        for work in Album.objects.only('pk', 'deprecated_composer_id').all()
        if work.deprecated_composer_id != 1
    ])

class Migration(migrations.Migration):

    dependencies = [
        ('mangaki', '0043_auto_20160410_2002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='composer',
            new_name='deprecated_composer',
        ),
        migrations.RunPython(code=populate_staff, reverse_code=migrations.RunPython.noop),
    ]
