# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-10 20:21
from __future__ import unicode_literals

from django.db import migrations, models

def move_anidb_aid_to_work(apps, schema_editor):
    Anime = apps.get_model("mangaki", "Anime")

    # The anidb_aid field is now in the Work base class, while the deprecated_anidb_aid
    # is in the two derived classes and contains the value of interest.
    for anime in Anime.objects.all():
        anime.anidb_aid = anime.deprecated_anidb_aid
        anime.save()

def move_anidb_aid_from_work(apps, schema_editor):
    Anime = apps.get_model("mangaki", "Anime")

    for anime in Anime.objects.all():
        anime.deprecated_anidb_aid = anime.anidb_aid
        anime.save()


class Migration(migrations.Migration):

    dependencies = [
        ('mangaki', '0045_migrate_catalog_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anime',
            old_name='anidb_aid',
            new_name='deprecated_anidb_aid',
        ),
        migrations.AddField(
            model_name='work',
            name='anidb_aid',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.RunPython(move_anidb_aid_to_work, reverse_code=move_anidb_aid_from_work),
    ]
