# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-10 20:25
from __future__ import unicode_literals

from django.db import migrations, models


def move_vgmdb_aid_to_work(apps, schema_editor):
    Album = apps.get_model("mangaki", "Album")

    # The vgmdb_aid field is now in the Work base class, while the deprecated_vgmdb_aid
    # is in the two derived classes and contains the value of interest.
    for album in Album.objects.all():
        album.vgmdb_aid = album.deprecated_vgmdb_aid
        album.save()


def move_vgmdb_aid_from_work(apps, schema_editor):
    Album = apps.get_model("mangaki", "Album")

    for album in Album.objects.all():
        album.deprecated_vgmdb_aid = album.vgmdb_aid
        album.save()


class Migration(migrations.Migration):

    dependencies = [
        ('mangaki', '0046_migrate_anidb_aid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='vgmdb_aid',
            new_name='deprecated_vgmdb_aid',
        ),
        migrations.AddField(
            model_name='work',
            name='vgmdb_aid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RunPython(move_vgmdb_aid_to_work, reverse_code=move_vgmdb_aid_from_work),
    ]
