# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-10 20:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mangaki', '0047_migrate_vgmdb_aid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anime',
            old_name='editor',
            new_name='deprecated_editor',
        ),
        migrations.RenameField(
            model_name='manga',
            old_name='editor',
            new_name='deprecated_editor',
        ),
        migrations.AddField(
            model_name='work',
            name='editor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mangaki.Editor'),
        ),
    ]
