# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-10 20:45
from __future__ import unicode_literals

from django.db import migrations


def move_editor_to_work(apps, schema_editor):
    Work = apps.get_model("mangaki", "Work")
    Anime = apps.get_model("mangaki", "Anime")
    Manga = apps.get_model("mangaki", "Manga")
    Editor = apps.get_model("mangaki", "Editor")

    # The editor field is now in the Work base class, while the deprecated_editor
    # is in the two derived classes and contains the value of interest.
    for anime in Anime.objects.all():
        anime.editor = anime.deprecated_editor
        anime.save()
    for manga in Manga.objects.all():
        manga.editor = Editor.objects.get_or_create(title=manga.deprecated_editor)[0]
        manga.save()


def move_editor_from_work(apps, schema_editor):
    Work = apps.get_model("mangaki", "Work")
    Anime = apps.get_model("mangaki", "Anime")
    Manga = apps.get_model("mangaki", "Manga")

    for anime in Anime.objects.all():
        anime.deprecated_editor = anime.editor
        anime.save()
    for manga in Manga.objects.all():
        manga.deprecated_editor = manga.editor.title
        manga.save()


class Migration(migrations.Migration):

    dependencies = [
        ('mangaki', '0048_migrate_editor'),
    ]

    operations = [
        migrations.RunPython(move_editor_to_work, reverse_code=move_editor_from_work),
    ]
