# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-10 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangaki', '0049_populate_work_editor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editor',
            name='title',
            field=models.CharField(db_index=True, max_length=33),
        ),
    ]
