# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-16 09:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mangaki', '0052_populate_work_studio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='anime_type',
            field=models.TextField(blank=True, max_length=42),
        ),
        migrations.AlterField(
            model_name='work',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mangaki.Category'),
        ),
        migrations.AlterField(
            model_name='work',
            name='nb_episodes',
            field=models.TextField(blank=True, default='Inconnu', max_length=16),
        ),
        migrations.AlterField(
            model_name='work',
            name='vo_title',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
