# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-16 20:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mangaki', '0053_auto_20160416_0907'),
        ('mangaki', '0038_auto_20160416_0930'),
    ]

    operations = [
    ]
