# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-16 21:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mangaki', '0001_squashed_0054_merge'),
        ('mangaki', '0037_artistspelling'),
    ]

    operations = [
    ]
