# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-02 20:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mangaki', '0036_trgm'),
        ('mangaki', '0001_squashed_0055_merge'),
    ]

    operations = [
    ]
