# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-02 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irl', '0006_events_on_work'),
        ('mangaki', '0056_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='album',
            field=models.ManyToManyField(to='mangaki.Work'),
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Anime',
        ),
        migrations.DeleteModel(
            name='Manga',
        ),
    ]
