# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-16 14:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mangaki', '0057_auto_20160702_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de publication')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FAQTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(unique=True)),
                ('theme', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='faqentry',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='mangaki.FAQTheme'),
        ),
    ]
