# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-07 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mangaki', '0056_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name='Date de publication')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FAQTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='Date de publication')),
            ],
        ),
        migrations.AddField(
            model_name='faqentry',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mangaki.FAQTheme'),
        ),
    ]
