# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-07 09:13
from __future__ import unicode_literals

from django.db import migrations
import mangaki.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mangaki', '0056_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='category',
            field=mangaki.fields.CategoryField(),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
