# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-17 17:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mangaki', '0057_auto_20160702_2048'),
        ('mangaki', '0057_auto_20160716_1417'),
    ]

    operations = [
    ]