# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-13 12:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mangaki', '0057_auto_20160607_1215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faqtheme',
            old_name='text',
            new_name='theme',
        ),
        migrations.AlterField(
            model_name='faqentry',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mangaki.Faqtheme'),
        ),
    ]
