# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-11 09:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mangaki', '0057_auto_20160702_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('work_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mangaki.Work')),
                ('deprecated_catalog_number', models.CharField(max_length=20)),
                ('deprecated_vgmdb_aid', models.IntegerField(blank=True, null=True)),
                ('deprecated_composer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='composer', to='mangaki.Artist')),
            ],
            bases=('mangaki.work',),
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('work_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mangaki.Work')),
                ('deprecated_origin', models.CharField(choices=[('japon', 'Japon'), ('coree', 'Coree'), ('france', 'France'), ('chine', 'Chine'), ('usa', 'USA'), ('allemagne', 'Allemagne'), ('taiwan', 'Taiwan'), ('espagne', 'Espagne'), ('angleterre', 'Angleterre'), ('hong-kong', 'Hong Kong'), ('italie', 'Italie'), ('inconnue', 'Inconnue'), ('intl', 'International')], default='', max_length=10)),
                ('deprecated_nb_episodes', models.TextField(default='Inconnu', max_length=16)),
                ('deprecated_anime_type', models.TextField(default='', max_length=42)),
                ('deprecated_anidb_aid', models.IntegerField(default=0)),
                ('deprecated_author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='authored', to='mangaki.Artist')),
                ('deprecated_composer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='composed', to='mangaki.Artist')),
                ('deprecated_director', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='directed', to='mangaki.Artist')),
                ('deprecated_editor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mangaki.Editor')),
                ('deprecated_genre', models.ManyToManyField(to='mangaki.Genre')),
                ('deprecated_studio', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mangaki.Studio')),
            ],
            bases=('mangaki.work',),
        ),
        migrations.CreateModel(
            name='ColdStartRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('like', "J'aime"), ('dislike', "Je n'aime pas"), ('dontknow', 'Je ne connais pas')], max_length=8)),
                ('date', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coldstartrating', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('work_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mangaki.Work')),
                ('deprecated_origin', models.CharField(choices=[('japon', 'Japon'), ('coree', 'Coree'), ('france', 'France'), ('chine', 'Chine'), ('usa', 'USA'), ('allemagne', 'Allemagne'), ('taiwan', 'Taiwan'), ('espagne', 'Espagne'), ('angleterre', 'Angleterre'), ('hong-kong', 'Hong Kong'), ('italie', 'Italie'), ('inconnue', 'Inconnue'), ('intl', 'International')], max_length=10)),
                ('deprecated_vo_title', models.CharField(max_length=128)),
                ('deprecated_manga_type', models.TextField(blank=True, choices=[('seinen', 'Seinen'), ('shonen', 'Shonen'), ('shojo', 'Shojo'), ('yaoi', 'Yaoi'), ('sonyun-manhwa', 'Sonyun-Manhwa'), ('kodomo', 'Kodomo'), ('ecchi-hentai', 'Ecchi-Hentai'), ('global-manga', 'Global-Manga'), ('manhua', 'Manhua'), ('josei', 'Josei'), ('sunjung-sunjeong', 'Sunjung-Sunjeong'), ('chungnyun', 'Chungnyun'), ('yuri', 'Yuri'), ('dojinshi-parodie', 'Dojinshi-Parodie'), ('manhwa', 'Manhwa'), ('yonkoma', 'Yonkoma')], max_length=16)),
                ('deprecated_editor', models.CharField(max_length=32)),
                ('deprecated_genre', models.ManyToManyField(to='mangaki.Genre')),
                ('deprecated_mangaka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drew', to='mangaki.Artist')),
                ('deprecated_writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wrote', to='mangaki.Artist')),
            ],
            bases=('mangaki.work',),
        ),
        migrations.AlterField(
            model_name='track',
            name='album',
            field=models.ManyToManyField(to='mangaki.Album'),
        ),
        migrations.AddField(
            model_name='coldstartrating',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mangaki.Work'),
        ),
        migrations.AlterUniqueTogether(
            name='coldstartrating',
            unique_together=set([('user', 'work')]),
        ),
    ]
