# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mangaki', '0058_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mangaki.Category'),
        ),
        migrations.AlterField(
            model_name='work',
            name='editor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='mangaki.Editor'),
        ),
        migrations.AlterField(
            model_name='work',
            name='studio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='mangaki.Studio'),
        ),
    ]
