# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-13 12:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mangaki', '0058_auto_20160613_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqentry',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mangaki.Faqtheme'),
        ),
    ]
