# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-29 21:06
from __future__ import unicode_literals

import os

from django.conf import settings
from django.db import migrations, models


def save_poster_path(apps, schema_editor):
    Work = apps.get_model("mangaki", "Work")
    db_alias = schema_editor.connection.alias
    for work in Work.objects.using(db_alias):
        path = 'posters/{:d}.jpg'.format(work.id)
        if os.path.isfile(os.path.join(settings.MEDIA_ROOT, path)):
            work.int_poster.name = path
            work.save(using=db_alias, update_fields=['int_poster'])


class Migration(migrations.Migration):

    dependencies = [
        ('mangaki', '0059_auto_20161029_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='int_poster',
            field=models.FileField(blank=True, null=True, upload_to='posters/'),
        ),
        migrations.RunPython(
            save_poster_path,
            migrations.RunPython.noop,
            atomic=True,
        ),
    ]
