# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 15:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mangaki', '0060_work_poster'),
        ('mangaki', '0059_auto_20161112_1448'),
    ]

    operations = [
    ]
