# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-28 14:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mangaki', '0060_auto_20160613_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqentry',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thème', to='mangaki.FAQTheme'),
        ),
    ]
