# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 21:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mangaki', '0061_merge_20161112_1539'),
        ('mangaki', '0057_auto_20160721_1254'),
    ]

    operations = [
    ]
