# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-21 12:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mangaki', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColdStartRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('like', "J'aime"), ('dislike', "Je n'aime pas"), ('dontknow', 'Je ne connais pas')], max_length=8)),
                ('date', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coldstartrating', to=settings.AUTH_USER_MODEL)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mangaki.Work')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='coldstartrating',
            unique_together=set([('user', 'work')]),
        ),
    ]
