# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-25 13:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mangaki', '0063_squashed_0058_auto_20160721_1353_to_0068_auto_20160729_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trope', models.CharField(max_length=320)),
                ('author', models.CharField(max_length=80)),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mangaki.Work')),
            ],
        ),
    ]
