# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-28 08:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mangaki', '0064_work_have_anidb_aid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='have_anidb_aid',
        ),
    ]
