# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-28 08:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mangaki', '0066_work_have_anidb_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='have_anidb_id',
            new_name='have_anidb_aid',
        ),
    ]
