# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 10:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mangaki', '0066_auto_20170311_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='score',
        ),
    ]
