# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mangaki', '0067_remove_profile_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktitle',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mangaki.Language'),
        ),
    ]
