# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-29 17:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mangaki', '0067_auto_20160728_0855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='nb_works_linked',
        ),
        migrations.RemoveField(
            model_name='work',
            name='have_anidb_aid',
        ),
    ]
