# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 19:11
from __future__ import unicode_literals

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangaki', '0068_auto_20170422_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='title_search',
            field=django.contrib.postgres.search.SearchVectorField(default='', verbose_name='title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worktitle',
            name='title_search',
            field=django.contrib.postgres.search.SearchVectorField(default='', verbose_name='title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='work',
            name='ext_poster',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.RunSQL(
            """
            CREATE TRIGGER mangaki_work_title_tsvectorupdate
                BEFORE INSERT OR UPDATE
                ON mangaki_work
                FOR EACH ROW EXECUTE PROCEDURE
            tsvector_update_trigger(title_search, 'pg_catalog.simple', title);
            CREATE TRIGGER mangaki_worktitle_title_tsvectorupdate
                BEFORE INSERT OR UPDATE
                ON mangaki_worktitle
                FOR EACH ROW EXECUTE PROCEDURE
            tsvector_update_trigger(title_search, 'pg_catalog.simple', title);
            UPDATE mangaki_work
            SET title_search = to_tsvector('simple', COALESCE(title, ''));
            UPDATE mangaki_worktitle
            SET title_search = to_tsvector('simple', COALESCE(title, ''));
            CREATE INDEX mangaki_work_title_tsv_index
                ON mangaki_work USING GIN (title_search);
            CREATE INDEX mangaki_worktitle_title_tsv_index
                ON mangaki_worktitle USING GIN (title_search);
            """,
            """
            DROP TRIGGER mangaki_work_title_tsvectorupdate ON mangaki_work;
            DROP TRIGGER mangaki_worktitle_title_tsvectorupdate ON mangaki_worktitle;
            DROP INDEX mangaki_work_title_tsv_index;
            DROP INDEX mangaki_worktitle_title_tsv_index;
            """)
    ]
