# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-10 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangaki', '0068_auto_20170422_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='research_ok',
            field=models.BooleanField(default=True),
        ),
    ]
