# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-30 07:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mangaki', '0068_auto_20170422_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkCluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_on', models.DateTimeField(auto_now=True)),
                ('merged_on', models.DateTimeField(auto_now=True)),
                ('checker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checker', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('works', models.ManyToManyField(to='mangaki.Work')),
            ],
        ),
    ]
