# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-09 21:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mangaki', '0069_profile_research_ok'),
        ('mangaki', '0069_auto_20170501_1911'),
    ]

    operations = [
    ]
