# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 00:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mangaki', '0070_merge_20170609_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=30)),
                ('ext_lang', models.CharField(db_index=True, null=True, default=None, max_length=8)),
            ],
        ),
        migrations.RemoveField(
            model_name='language',
            name='anidb_language',
        ),
        migrations.RemoveField(
            model_name='language',
            name='iso639',
        ),
        migrations.AddField(
            model_name='language',
            name='code',
            field=models.CharField(db_index=True, default=None,
                                   help_text='ISO639-1 code or custom (e.g. x-jat, x-kot, x-ins)',
                                   max_length=10,
                                   null=True,
                                   unique=True),
        ),
        migrations.AddField(
            model_name='extlanguage',
            name='lang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mangaki.Language'),
        ),
        migrations.AlterUniqueTogether(
            name='extlanguage',
            unique_together=set([('ext_lang', 'source')]),
        ),
        migrations.AddField(
            model_name='worktitle',
            name='ext_language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mangaki.ExtLanguage'),
        ),
        migrations.AlterField(
            model_name='work',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='worktitle',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='work',
            name='ext_synopsis',
            field=models.TextField(blank=True, default=''),
        ),
    ]
