# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-10 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangaki', '0070_merge_20170609_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='iso639',
        ),
        migrations.AddField(
            model_name='language',
            name='lang_code',
            field=models.CharField(db_index=True, default='unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='language',
            name='anidb_language',
            field=models.CharField(blank=True, db_index=True, max_length=8, unique=True),
        ),
    ]
