# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-10 06:07
from __future__ import unicode_literals

from django.db import migrations

UNK_VALUE = 'unknown'

# AniDB → ISO639-1 or custom.
lang_map = {
    'al': 'sq',
    'ar': 'ar',
    'bd': 'bn',
    'pt-BR': 'pt',
    'bg': 'bg',
    'ca': 'ca',
    'zh-x-yue': 'zh',
    'zh-x-cmn': 'zh',
    'zh-Hans': 'zh',
    'zh-x-nan': 'zh',
    'zh-Hant': 'zh',
    'zh': 'zh',
    'hr': 'hr',
    'cs': 'cs',
    'da': 'da',
    'nl': 'nl',
    'en': 'en',
    'et': 'et',
    'fi': 'fi',
    'fr': 'fr',
    'gl': 'gl',
    'ka': 'ka',
    'de': 'de',
    'el': 'el',
    'he': 'he',
    'hu': 'hu',
    'is': 'is',
    'id': 'id',
    'x-in': 'x-in',  # Instrumental
    'it': 'it',
    'ja': 'ja',
    'x-jat': 'x-jat',  # x-jat is transliteral Japanese
    'jv': 'jv',
    'ko': 'ko',
    'x-kot': 'x-kot',  # x-kot is transliteral Korean
    'la': 'la',
    'es-LA': 'la',
    'lv': 'lv',
    'lt': 'lt',
    'my': 'ms',
    'no': 'no',
    'pl': 'pl',
    'pt': 'pt',
    'ro': 'ro',
    'ru': 'ru',
    'sr': 'sr',
    'sk': 'sk',
    'sl': 'sl',
    'es': 'es',
    'sv': 'sv',
    'ta': 'ta',
    'tt': 'tt',
    'th': 'th',
    'tr': 'tr',
    'uk': 'uk',
    'x-unk': UNK_VALUE,
    'x-other': UNK_VALUE,
    'vi': 'vi'
}


def add_languages(apps, _):
    Language = apps.get_model('mangaki', 'Language')
    Language.objects.bulk_create([
        Language(anidb_language=x, lang_code=y)
        for x, y in lang_map.items()
    ])


def remove_languages(apps, _):
    Language = apps.get_model('mangaki', 'Language')
    for anidb_lang, lang_code in lang_map.items():
        Language.objects.filter(anidb_language=anidb_lang,
                                lang_code=lang_code).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('mangaki', '0071_auto_20170610_0607'),
    ]

    operations = [
        migrations.RunPython(add_languages, remove_languages)
    ]
