# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-30 18:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mangaki', '0071_fix_mal_cdn'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkCluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_on', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('unprocessed', 'Non traité'), ('accepted', 'Accepté'), ('rejected', 'Rejeté')], default='unprocessed', max_length=11)),
                ('merged_on', models.DateTimeField(blank=True, null=True)),
                ('checker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reported_clusters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelManagers(
            name='work',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='work',
            name='redirect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mangaki.Work'),
        ),
        migrations.AddField(
            model_name='workcluster',
            name='resulting_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to='mangaki.Work'),
        ),
        migrations.AddField(
            model_name='workcluster',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workcluster',
            name='works',
            field=models.ManyToManyField(to='mangaki.Work'),
        ),
    ]
