# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 11:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mangaki', '0073_rename_synonyme_to_synonym'),
        ('mangaki', '0071_fix_mal_cdn'),
    ]

    operations = [
    ]
