# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-10 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangaki', '0074_worktitle_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='title',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='worktitle',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=300),
        ),
    ]
