# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 09:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mangaki', '0072_auto_20170530_1837'),
        ('mangaki', '0074_merge_20170621_1103'),
    ]

    operations = [
    ]
