# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 23:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mangaki', '0075_titles_are_longer_than_expected'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktitle',
            name='ext_language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mangaki.ExtLanguage'),
        ),
        migrations.AlterField(
            model_name='extlanguage',
            name='ext_lang',
            field=models.CharField(db_index=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.CharField(db_index=True, default=None, help_text='ISO639-1 code or custom (e.g. x-jat, x-kot, x-ins)', max_length=10),
        ),
        migrations.AlterField(
            model_name='work',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='worktitle',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
