# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangaki', '0076_auto_20170628_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='enddate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
