# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 23:18
from __future__ import unicode_literals

from django.db import migrations


def rename_synonyme_to_synonym(apps, schema):
    WorkTitle = apps.get_model('mangaki', 'WorkTitle')

    db_alias = schema.connection.alias
    WorkTitle.objects.using(db_alias).filter(type='synonyme').update(type='synonym')


def rename_synonym_to_synonyme(apps, schema):
    WorkTitle = apps.get_model('mangaki', 'WorkTitle')

    db_alias = schema.connection.alias
    WorkTitle.objects.using(db_alias).filter(type='synonym').update(type='synonyme')


class Migration(migrations.Migration):

    dependencies = [
        ('mangaki', '0076_auto_20170610_2317'),
    ]

    operations = [
        migrations.RunPython(rename_synonyme_to_synonym, rename_synonym_to_synonyme)
    ]
