# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangaki', '0077_add_work_enddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
