# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangaki', '0077_add_work_enddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='anidb_tag_id',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
