# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangaki', '0079_add_tags_anidb_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='anilist_id',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
