# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 01:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mangaki', '0079_add_tags_anidb_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mangaki.Editor'),
        ),
        migrations.AlterField(
            model_name='work',
            name='studio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mangaki.Studio'),
        ),
    ]
