# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 05:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mangaki', '0079_add_tags_anidb_id'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='work',
            managers=[
            ],
        ),
    ]
