# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 11:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mangaki', '0080_auto_20170719_0511'),
        ('mangaki', '0080_save_studio_and_editor_on_work'),
    ]

    operations = [
    ]
