# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 12:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mangaki', '0080_add_relatedwork_model'),
        ('mangaki', '0081_merge_20170720_1125'),
    ]

    operations = [
    ]
