# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-07 17:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mangaki', '0082_merge_20170720_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agrees', models.BooleanField(default=False)),
                ('needs_help', models.BooleanField(default=False)),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mangaki.Suggestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
