# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-08 17:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mangaki', '0083_add_evidence_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='workcluster',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origin_suggestion', to='mangaki.Suggestion'),
        ),
    ]
