# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-27 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangaki', '0085_add_anilist_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='anilist_creator_id',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='relatedwork',
            name='type',
            field=models.CharField(choices=[('', 'Inconnu'), ('prequel', 'Préquelle'), ('sequel', 'Suite'), ('summary', 'Résumé'), ('side_story', 'Histoire parallèle'), ('parent_story', 'Histoire mère'), ('alternative_setting', 'Univers alternatif'), ('same_setting', 'Univers commun'), ('other', 'Spécial'), ('adaptation', 'Adaptation')], default='', max_length=20, verbose_name='Type de relation'),
        ),
    ]
