# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-24 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangaki', '0087_auto_20171023_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='keyboard_shortcuts_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
