# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-25 17:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mangaki', '0088_auto_20171225_1534'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reference',
            unique_together=set([('work', 'source', 'identifier')]),
        ),
    ]
