# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-25 17:34
from __future__ import unicode_literals

from django.db import migrations, models


def remove_duplicates(apps, schema_editor):
    Reference = apps.get_model('mangaki', 'Reference')
    db_alias = schema_editor.connection.alias

    unique_fields = ['work', 'source', 'identifier']

    duplicates = (Reference.objects.using(db_alias)
                                   .values(*unique_fields)
                                   .order_by()
                                   .annotate(max_id=models.Max('id'),
                                             count_id=models.Count('id'))
                                   .filter(count_id__gt=1)
                                   .iterator())

    for duplicate in duplicates:
        (Reference.objects.using(db_alias)
                          .filter(**{x: duplicate[x] for x in unique_fields})
                          .exclude(id=duplicate['max_id'])
                          .delete())


class Migration(migrations.Migration):

    dependencies = [
        ('mangaki', '0088_auto_20171225_1534'),
    ]

    operations = [
        migrations.RunPython(remove_duplicates,
                             reverse_code=migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='reference',
            unique_together=set([('work', 'source', 'identifier')]),
        ),
    ]
