# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-20 10:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mangaki', '0090_auto_20180507_2121'),
        ('mangaki', '0090_auto_20180508_0941'),
    ]

    operations = [
    ]
