# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-09 15:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mangaki', '0089_auto_20171225_1734'),
        ('mangaki', '0090_auto_20180508_0941'),
    ]

    operations = [
    ]
