# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-08 09:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mangaki', '0090_profile_keyboard_shortcuts_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchissue',
            name='user',
        ),
        migrations.DeleteModel(
            name='SearchIssue',
        ),
    ]
