# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-21 23:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mangaki', '0091_merge_20180509_1527'),
        ('mangaki', '0091_merge_20180520_1055'),
    ]

    operations = [
    ]
