# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-07 21:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mangaki', '0092_userarchive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userarchive',
            old_name='created_on',
            new_name='updated_on',
        ),
    ]
