# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-08 09:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mangaki', '0093_auto_20180507_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighborship',
            name='neighbor',
        ),
        migrations.RemoveField(
            model_name='neighborship',
            name='user',
        ),
        migrations.DeleteModel(
            name='Neighborship',
        ),
    ]
