# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-08 15:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mangaki', '0094_auto_20180508_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mangaki.Work')),
            ],
        ),
        migrations.AlterModelOptions(
            name='faqentry',
            options={'verbose_name_plural': 'FAQ entries'},
        ),
        migrations.AlterModelOptions(
            name='faqtheme',
            options={'verbose_name_plural': 'FAQ themes'},
        ),
        migrations.AlterField(
            model_name='top',
            name='category',
            field=models.CharField(choices=[('directors', 'Directors'), ('authors', 'Authors'), ('composers', 'Composers')], max_length=10, unique_for_date='date'),
        ),
        migrations.AlterUniqueTogether(
            name='externalrating',
            unique_together=set([('work', 'user')]),
        ),
    ]
