# Generated by Django 2.2.24 on 2021-12-01 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mangaki', '0096_fix_mal_cdn'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(related_name='friends', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='work',
            name='redirect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mangaki.Work'),
        ),
        migrations.AlterField(
            model_name='workcluster',
            name='resulting_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clusters', to='mangaki.Work'),
        ),
        migrations.AlterField(
            model_name='workcluster',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='worktitle',
            name='ext_language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mangaki.ExtLanguage'),
        ),
        migrations.AlterField(
            model_name='worktitle',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mangaki.Language'),
        ),
        migrations.DeleteModel(
            name='ColdStartRating',
        ),
    ]
