# Generated by Django 2.1.2 on 2018-10-11 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mangaki', '0097_profile_policy'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coldstartrating',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='coldstartrating',
            name='user',
        ),
        migrations.RemoveField(
            model_name='coldstartrating',
            name='work',
        ),
        migrations.AlterField(
            model_name='work',
            name='redirect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mangaki.Work'),
        ),
        migrations.AlterField(
            model_name='workcluster',
            name='resulting_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clusters', to='mangaki.Work'),
        ),
        migrations.AlterField(
            model_name='workcluster',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='worktitle',
            name='ext_language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mangaki.ExtLanguage'),
        ),
        migrations.AlterField(
            model_name='worktitle',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mangaki.Language'),
        ),
        migrations.DeleteModel(
            name='ColdStartRating',
        ),
    ]
