# Generated by Django 2.2.27 on 2022-08-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangaki', '0098_auto_20220801_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
