# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-09 18:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mangaki', '0001_squashed_0026_auto_20160108_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('premiere', 'avant-première'), ('screening', 'projection'), ('release', 'sortie'), ('tv', 'diffusion')], max_length=9)),
                ('language', models.CharField(choices=[('vf', 'VF'), ('vostfr', 'VOSTFR'), ('vosta', 'VOSTA')], max_length=6)),
                ('channel', models.CharField(blank=True, default='', max_length=16)),
                ('date', models.DateTimeField()),
                ('link', models.URLField(blank=True, default='')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mangaki.Anime')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Titre')),
                ('address', models.TextField(verbose_name='Adresse')),
                ('postal_code', models.CharField(max_length=5, verbose_name='Code postal')),
                ('city', models.CharField(max_length=64, verbose_name='Ville')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='irl.Location'),
        ),
    ]
