# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-07 14:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('irl', '0003_auto_20160124_1919'),
        ('irl', '0004_event_attendees'),
    ]

    operations = [
    ]
