# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-16 09:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('irl', '0005_merge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='anime',
            new_name='work',
        ),
        migrations.AlterField(
            model_name='event',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mangaki.Work'),
        ),
    ]
