# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-08 09:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('irl', '0007_auto_20180508_0950'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
