---
dehydrated_user: 'dehydrated'
dehydrated_group: 'dehydrated'
dehydrated_home: '/home/{{ dehydrated_user }}/'
dehydrated_version: '0.6.5'
dehydrated_checksum: 'sha256:10aabd0027450bc70a18e49acaca7a9697e0cfb92368d3e508b7a4d6d69bfa35'

dehydrated_root: '/etc/dehydrated/'
