---
- name: reload supervisor
  become: true
  become_user: root
  supervisorctl: name={{ application_name }} state=present

- name: restart supervisor
  become: true
  become_user: root
  supervisorctl: name={{ application_name }} state=restarted
