version: 2
jobs:
  build:
    working_directory: ~/mangaki/
    docker:
      - image: circleci/python:3.7.7-stretch
      - image: circleci/postgres:9.6.10-alpine-ram
        environment:
          POSTGRES_USER: mangaki
          POSTGRES_DB: circle_test
    environment:
      TEST_REPORTS: /tmp/test-reports
      ARTIFACTS: /tmp/artifacts
      MATPLOTLIBRC: tests
    steps:
      - checkout:
          path: ~/mangaki
      - restore_cache:
          key: deps-{{ .Branch }}-{{ checksum "~/mangaki/poetry.lock" }}
      - run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common python3-dev libopenblas-dev postgresql-client
          poetry install
      - save_cache:
          key: deps-{{ .Branch }}-{{ checksum "~/mangaki/poetry.lock" }}
          paths:
            - /home/circleci/.cache/pypoetry/virtualenvs
      - run:
          name: Waiting for Postgres to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 5432 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Postgres && exit 1
      - run: |
          psql -h localhost -U mangaki -d circle_test -c "create extension if not exists pg_trgm;
                                create extension if not exists unaccent"
          cp ~/mangaki/.circle_mangaki_settings.ini mangaki/settings.ini
          poetry run ./mangaki/manage.py migrate
          poetry run ./mangaki/manage.py ranking
          poetry run ./mangaki/manage.py top --all
          mkdir -p $TEST_REPORTS
          mkdir -p $ARTIFACTS
          poetry run ./mangaki/manage.py collectstatic --no-input
          poetry run py.test --cov-report=xml --cov=mangaki --junitxml=$TEST_REPORTS/junit.xml mangaki/
          cp coverage.xml $ARTIFACTS/
          bash <(curl -s https://codecov.io/bash)
      - store_artifacts:
          path: /tmp/artifacts
          destination: build
      - store_test_results:
          path: /tmp/test-reports

  push_beta:
    docker:
      - image: mangaki/mangaki-deploy-environment:v2
    working_directory: ~/mangaki
    steps:
      - checkout:
          path: ~/mangaki
      - add_ssh_keys:
          fingerprints:
            - "6b:53:99:19:90:0b:26:94:68:aa:89:6f:be:54:01:41"
      - run:
          name: Deploying the beta instance using Ansible
          command: |
            poetry run ./provisioning/scripts/deploy_beta.sh
workflows:
  version: 2
  build_and_test_and_deploy:
    jobs:
      - build
      - push_beta:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - raito/cci2-deploy
