---
- include: create_users.yml
  become: true
  become_user: root

- include: install_packages.yml
  become: true
  become_user: root
  tags: packages

- include: setup_supervisor.yml
  become: true
  become_user: root
  tags: deploy

- include: setup_systemd.yml
  become: true
  become_user: root
  tags: deploy

- name: Create static root
  become: true
  become_user: root
  file:
    path: "{{ static_root }}"
    state: directory
    owner: "{{ web_user }}"
    group: "{{ web_group }}"
    mode: 0755

# Set up non-root elements using `web_user`
- block:
    - include: setup_git.yml
      tags: deploy

    - name: Install pip requirements
      pip:
        requirements: "{{ requirements_file }}"
        virtualenv: "{{ virtualenv_path }}"
        # we use the system lxml package due to heavy build requirements
        virtualenv_site_packages: true
        virtualenv_python: python3
      tags: packages

    - name: Install gunicorn
      pip: virtualenv={{ virtualenv_path }} name=gunicorn
      tags: packages,deploy

    - name: Copy settings.ini
      template:
        src: settings.ini.j2
        dest: "{{ git_dest }}/mangaki/settings.ini"
        mode: 0600
        owner: "{{ web_user }}"
        group: "{{ web_group }}"
        backup: true

    - name: Initialize database
      django_manage:
        command: "migrate"
        app_path: "{{ git_dest }}/mangaki"
        virtualenv: "{{ virtualenv_path }}"

    - name: Collect static files
      django_manage:
        command: "collectstatic"
        app_path: "{{ git_dest }}/mangaki"
        virtualenv: "{{ virtualenv_path }}"

  become: true
  become_user: "{{ web_user }}"

- name: Run Mangaki application server (gunicorn)
  supervisorctl: name=mangaki state=started
  become: true
  become_user: root
