---
- name: Ensure supervisor is installed
  apt: name=supervisor state=present
  tags: packages

- name: Create the supervisor config file
  template:
    src: supervisor.conf.j2
    dest: /etc/supervisor/conf.d/{{ application_name }}.conf
    mode: 0600
    backup: true
  notify:
    - reload supervisor
