---
- name: Setup task's timer and service.
  template:
    src: 'etc/systemd/system/cron.{{ item }}.j2'
    dest: '/etc/systemd/system/{{ cron_name }}.{{ item }}'
    mode: '0644'
    owner: 'root'
    group: 'root'
  become: true
  with_items: ['timer', 'service']

- name: Enable task's timer.
  systemd:
    name: '{{ cron_name }}.timer'
    state: '{{ cron_enabled|bool|ternary("started", "stopped") }}'
    enabled: '{{ cron_enabled|bool }}'
    daemon_reload: true
  become: true
