---
- name: Create group.
  group:
    name: '{{ dehydrated_group }}'
    state: 'present'
  become: true

- name: Create user.
  user: 
    name: '{{ dehydrated_user }}'
    group: '{{ dehydrated_group }}'
    state: 'present'
    home: '{{ dehydrated_home }}'
    move_home: true
  become: true

- name: Ensure dependencies are installed and up-to-date.
  apt:
    name: '{{ item }}'
    state: 'latest'
  with_items: ['openssl', 'curl']
  become: true

- name: Download archive from GitHub.
  get_url:
    url: 'https://github.com/lukas2511/dehydrated/archive/v{{ dehydrated_version }}.tar.gz'
    checksum: '{{ dehydrated_checksum }}'
    dest: '{{ dehydrated_home }}/dehydrated-{{ dehydrated_version }}.tar.gz'
    owner: '{{ dehydrated_user }}'
    group: '{{ dehydrated_user }}'
    mode: '0644'
  become: true
  become_user: '{{ dehydrated_user }}'

- name: Extract archive.
  unarchive:
    src: '{{ dehydrated_home }}/dehydrated-{{ dehydrated_version }}.tar.gz'
    dest: '{{ dehydrated_home }}'
    owner: '{{ dehydrated_user }}'
    group: '{{ dehydrated_user }}'
    mode: '0755'
    remote_src: true
  become: true
  become_user: '{{ dehydrated_user }}'

- name: Install script.
  copy:
    src: '{{ dehydrated_home }}/dehydrated-{{ dehydrated_version }}/dehydrated'
    dest: '/usr/local/bin/dehydrated'
    remote_src: true
    owner: 'root'
    group: 'root'
    mode: '0755'
  become: true
