---
- name: Generate dhparams
  command: /usr/bin/openssl dhparam -out {{ ssl_dhparam }} 2048
  args:
    creates: '{{ ssl_dhparam }}'
  become: true
  become_user: root


- name: Create the nginx with TLS configuration for Mangaki
  become: true
  become_user: root
  template:
    src: "mangaki.j2"
    dest: /etc/nginx/sites-available/{{ application_name }}
    backup: yes
  notify: reload nginx
