---
- block:
  - name: Create the HTTPS NGINX configuration
    template:
      src: "https.j2"
      dest: /etc/nginx/sites-available/{{ application_name }}.https
      backup: yes
    notify: reload nginx

  - name: Ensure the HTTPS application site is enabled
    file:
      src: /etc/nginx/sites-available/{{ application_name }}.https
      dest: /etc/nginx/sites-enabled/{{ application_name }}.https
      state: link
    notify: reload nginx

  become: true
  become_user: root
