---
- block:
    - name: create letsencrypt group
      group: name=letsencrypt state=present

    - name: create letsencrypt user
      user: name=letsencrypt group=letsencrypt state=present

    - name: grant rights on {{ letsencrypt_sh_root }}
      file: path={{ letsencrypt_sh_root }} owner=letsencrypt group=letsencrypt mode="u=rwx,g=rwx,o-rwx" state=directory

  become: true
  become_user: root

- name: ensure letsencrypt.sh dependencies are installed
  become: true
  become_user: root
  apt: name={{ item }} state=latest
  with_items:
    - openssl
    - curl
  tags: packages

# FIXME: Someday, we should rename letsencrypt.sh to dehydrated. Someday.
- name: install letsencrypt.sh
  become: true
  become_user: letsencrypt
  git:
    repo: https://github.com/lukas2511/dehydrated.git
    dest: "{{ letsencrypt_sh_root }}"
    version: "{{ letsencrypt_sh_version }}"

- name: setup acme wellknown directory
  file:
    path: "{{ acme_wellknown }}"
    state: directory
    owner: letsencrypt
    group: letsencrypt
    mode: 0755

- name: configure letsencrypt.sh
  template:
    src: "{{ item }}.j2"
    dest: "{{ letsencrypt_sh_root }}/{{ item }}"
    mode: 0600
    owner: "letsencrypt"
    group: "letsencrypt"
  with_items:
    - config
    - domains.txt


- name: generate certificates
  command: "{{ letsencrypt_sh_root }}/dehydrated --accept-terms -c"
  run_once: true
  become: true
  become_user: letsencrypt
  register: cert_result
  changed_when: '"skipping renew!" not in cert_result.stdout.lower()'

- name: Let's Encrypt is ready
  set_fact: 
    letsencrypt_ready: true

- name: set up timer to renew certificates
  template:
    src: regenerate-certificates.timer.j2
    dest: /etc/systemd/system/regenerate-certificates.timer
    mode: 0600
    backup: true

- name: Ensure that the renewing timer is enabled
  systemd: name=regenerate-certificates.timer enabled=yes daemon_reload=yes
