---

- name: Ensure "{{ item }}" is installed at the latest version
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - python3
    - python3-dev
    - python3-pip
    - python-virtualenv
