# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 19:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('mangaki', '0028_auto_20160124_1919'), ('mangaki', '0029_auto_20160124_1922')]

    dependencies = [
        ('mangaki', '0027_tops'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('work_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mangaki.Work')),
                ('catalog_number', models.CharField(max_length=20)),
                ('vgmdb_aid', models.IntegerField(blank=True, null=True)),
                ('composer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='composer', to='mangaki.Artist')),
            ],
            bases=('mangaki.work',),
        ),
        migrations.RemoveField(
            model_name='ost',
            name='work_ptr',
        ),
        migrations.RemoveField(
            model_name='track',
            name='ost',
        ),
        migrations.DeleteModel(
            name='OST',
        ),
        migrations.AddField(
            model_name='track',
            name='album',
            field=models.ManyToManyField(to='mangaki.Album'),
        ),
    ]
