# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-10 20:02
from __future__ import unicode_literals

from django.db import migrations, models

def move_manga_type_to_work(apps, schema_editor):
    Manga = apps.get_model("mangaki", "Manga")

    # The manga_type field is now in the Work base class, while the deprecated_manga_type
    # is in the two derived classes and contains the value of interest.
    for manga in Manga.objects.all():
        manga.manga_type = manga.deprecated_manga_type
        manga.save()

def move_manga_type_from_work(apps, schema_editor):
    Manga = apps.get_model("mangaki", "Manga")

    for manga in Manga.objects.all():
        manga.deprecated_manga_type = manga.manga_type
        manga.save()

class Migration(migrations.Migration):

    dependencies = [
        ('mangaki', '0042_auto_20160410_1953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manga',
            old_name='manga_type',
            new_name='deprecated_manga_type',
        ),
        migrations.AddField(
            model_name='work',
            name='manga_type',
            field=models.TextField(blank=True, choices=[('seinen', 'Seinen'), ('shonen', 'Shonen'), ('shojo', 'Shojo'), ('yaoi', 'Yaoi'), ('sonyun-manhwa', 'Sonyun-Manhwa'), ('kodomo', 'Kodomo'), ('ecchi-hentai', 'Ecchi-Hentai'), ('global-manga', 'Global-Manga'), ('manhua', 'Manhua'), ('josei', 'Josei'), ('sunjung-sunjeong', 'Sunjung-Sunjeong'), ('chungnyun', 'Chungnyun'), ('yuri', 'Yuri'), ('dojinshi-parodie', 'Dojinshi-Parodie'), ('manhwa', 'Manhwa'), ('yonkoma', 'Yonkoma')], max_length=16),
        ),
        migrations.RunPython(move_manga_type_to_work, reverse_code=move_manga_type_from_work),
    ]
