# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-10 21:01
from __future__ import unicode_literals

from django.db import migrations

def move_studio_to_work(apps, schema_editor):
    Anime = apps.get_model("mangaki", "Anime")

    # The studio field is now in the Work base class, while the deprecated_studio
    # is in the two derived classes and contains the value of interest.
    for anime in Anime.objects.all():
        anime.studio = anime.deprecated_studio
        anime.save()

def move_studio_from_work(apps, schema_editor):
    Anime = apps.get_model("mangaki", "Anime")

    for anime in Anime.objects.all():
        anime.deprecated_studio = anime.studio
        anime.save()


class Migration(migrations.Migration):

    dependencies = [
        ('mangaki', '0051_migrate_studio'),
    ]

    operations = [
        migrations.RunPython(move_studio_to_work, reverse_code=move_studio_from_work),
    ]
