# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-02 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irl', '0006_events_on_work'),
        ('mangaki', '0056_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='deprecated_composer',
        ),
        migrations.RemoveField(
            model_name='album',
            name='work_ptr',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='deprecated_author',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='deprecated_composer',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='deprecated_director',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='deprecated_editor',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='deprecated_genre',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='deprecated_studio',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='work_ptr',
        ),
        migrations.RemoveField(
            model_name='manga',
            name='deprecated_genre',
        ),
        migrations.RemoveField(
            model_name='manga',
            name='deprecated_mangaka',
        ),
        migrations.RemoveField(
            model_name='manga',
            name='deprecated_writer',
        ),
        migrations.RemoveField(
            model_name='manga',
            name='work_ptr',
        ),
        migrations.AlterField(
            model_name='track',
            name='album',
            field=models.ManyToManyField(to='mangaki.Work'),
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Anime',
        ),
        migrations.DeleteModel(
            name='Manga',
        ),
    ]
