---
- name: ensure apt cache is fresh (<= 1 hour)
  become: true
  become_user: root
  apt:
    update_cache: true
    cache_valid_time: 3600
  tags: packages


- name: ensure basic packages are installed
  become: true
  become_user: root
  apt: name={{ item }} state=latest
  with_items:
    - sudo
  tags: packages
