---
- name: Ensure apt cache and packages are up-to-date.
  hosts: all
  tasks:
    - name: "FIX: Ensure aptitude is installed."
      raw: apt-get install aptitude -y
      become: true

    - apt:
        upgrade: 'yes'
        update_cache: 'yes'
        cache_valid_time: 3600
      become: true

- name: Setup development servers.
  hosts: mangaki_dev
  roles:
    - role: mangaki_db
    - role: mangaki_source
    - role: mangaki_sync
    # In development mode, we start Celery through tmux rather than supervisor (by default, start_celery: true).
    - { role: mangaki_back, start_celery: false }

- name: Setup standalone servers.
  hosts: mangaki_standalone
  roles:
    - role: mangaki_db
    - role: mangaki_source
    - role: mangaki_sync
    - role: mangaki_front
    - role: mangaki_back
    - role: utils/nginx
    - role: utils/dehydrated
      when: 'mangaki_web_use_acme|bool'
    - role: mangaki_web
