---
- name: Ensure nginx is installed and up-to-date.
  apt:
    name: 'nginx'
    state: 'latest'
  become: true

- name: Ensure nginx default site is disabled.
  file:
    path: '/etc/nginx/sites-enabled/default'
    state: 'absent'
  become: true
  notify:
   - Test and reload nginx.

- name: Ensure nginx is running
  service:
    name: 'nginx'
    state: 'started'
    enabled: true
  become: true
