# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-10 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('url', models.CharField(max_length=512)),
                ('image', models.CharField(max_length=32, verbose_name='Nom image')),
            ],
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date']},
        ),
    ]
