# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irl', '0002_auto_20160110_2244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='partner',
            name='image',
            field=models.CharField(max_length=32, verbose_name='Fichier logo'),
        ),
    ]
